// app/layout.tsx (Server Component)
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { SkeletonTheme } from "react-loading-skeleton";
import ClientProvider from "@/components/ClientProvider";
import "keen-slider/keen-slider.min.css";
import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
// import fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // creates a CSS variable
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Brew Haven",
  description: "Generated by create next app",
  icons: { icon: "/coffee-logo.svg" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${playfair.variable}`}>
        <Navbar />
        <SkeletonTheme baseColor="#d6c1b1" highlightColor="#f2e4d9">
          <ClientProvider>{children}</ClientProvider>
        </SkeletonTheme>
        <Footer />
      </body>
    </html>
  );
}
