// app/layout.tsx (Server Component)
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import ClientProvider from "@/components/ClientProvider"; // client component wrapper

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Brew Haven",
  description: "Generated by create next app",
  icons: { icon: "/coffee-logo.svg" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ClientProvider>{children}</ClientProvider>
        <Footer />
      </body>
    </html>
  );
}
